apiVersion: apps/v1
kind: Deployment
metadata:
  name: ok31teto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ok31teto
  template:
    metadata:
      labels:
        app: ok31teto
    spec:
      containers:
      - image: okteto.dev/ok31teto:latest
        name: ok31teto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "805f3359-bf22-4286-a251-1507e7010edf"
        - name: Vless_Path
          value: "/jkdudkjbvij897"
        - name: Vmess_UUID
          value: "6a2462f4-f780-49ad-b8a8-8fd7f28882cc"
        - name: Vmess_Path
          value: "/uiyewojtre345"
        - name: Share_Path
          value: "/v2link"
