apiVersion: v1
kind: Service
metadata:
  name: ok31teto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ok31teto"
    port: 8080
  selector:
    app: ok31teto
